### ISSUE TITLE
After Application customizer deployment sites are not loading

### ISSUE THREAD

**Issue by Viipiin** [SharePoint/sp-dev-training-spfx-extensions#26]
Hi ,
I'm just trying to hide some command button in command bar using application customizer and deploying that extension tenant wide.But after deployment None of site is opening except app catalog. and once I delete the sppkg file from app cat all sites are working fine.I tried private mode/another machine but facing same issue .
Error Getting in dev tool are 
Refused to get unsafe header "SPClientServiceRequestDuration"
Refused to get unsafe header "SPRequestGuid"

**Comment by hugoabernier** [comment]
@Viipiin thanks for your question. This issue list is intended for questions related to samples in this repository. You may have better luck with the SP Dev Docs repository, or stack exchange. 

At this time, it is not supported to hide buttons -- not is it advisable to do so. The only exception is to hide or show your own command extensions, but you cannot affect system buttons. 

I hope this helps?
