### ISSUE TITLE
SharePoint Extensions not loaded at tenant level since this morning

### ISSUE THREAD

**Issue by IvanParedes365** [SharePoint/sp-dev-training-spfx-extensions#27]
Dear colleagues,

It seems there is an issue in some SPO tenants because SPFX extensions are not being loaded. JavaScript file is loaded but not executed.

I created a new SPFX extensions from scratch using last version and without any code other than the default one and it's the same. It's not possible to load SPFX extensions, so I assume that maybe the rolling out of a new feature is causing this effect.

Other users with same issue:
https://techcommunity.microsoft.com/t5/sharepoint-developer/listview-command-set-suddenly-disappeared-across-my-tenant/m-p/2350248/highlight/false#M10272

Could you please take a look and let us know if there is any workaround we could implement?

Thanks,
Ivan

**Comment by jorgereales** [comment]
Hello,

The issue referred by @IvanParedes365 is indeed affecting all the solutions in our corporate SPO tenant. We have realized that problem yesterday. Command sets disappear on previously working applications as soon as the cached version of the extension's JavaScript file is deleted. No network or console error appears, though.

Thanks,
Jorge

**Comment by andrewconnell** [comment]
This question is more about SPFx rather than an issue with this module. The SharePoint team doesn't monitor this repo as it's just a "hold" for the sample code in the associated Microsoft Learning module. Please submit your question to the appropriate SPFx developer support forum(s).
